//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehumidifierControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DehumidifierControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство отклонило дѣйствіе ({0}, {1}): {2}.
        /// </summary>
        internal static string ActionRejected {
            get {
                return ResourceManager.GetString("ActionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невѣрный адресъ.
        /// </summary>
        internal static string BadAddress {
            get {
                return ResourceManager.GetString("BadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Странный отвѣтъ на {0}..
        /// </summary>
        internal static string BadResponse {
            get {
                return ResourceManager.GetString("BadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токенъ — это 32 шестнадцатеричныя цифры.
        /// </summary>
        internal static string BadToken {
            get {
                return ResourceManager.GetString("BadToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: цѣлевая влажность — цѣлое число отъ {1} до {2}..
        /// </summary>
        internal static string CliBadHumidity {
            get {
                return ResourceManager.GetString("CliBadHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: нужно dim|bright (тусклая|яркая) и/или on|off (включить|выключить)..
        /// </summary>
        internal static string CliBadLight {
            get {
                return ResourceManager.GetString("CliBadLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: режимъ — smart, sleep или dry (умный, ночной, сушка)..
        /// </summary>
        internal static string CliBadMode {
            get {
                return ResourceManager.GetString("CliBadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: свойство — siid.piid для чтенія или siid.piid=значеніе для записи, напримѣръ 2.5 или 2.5=45..
        /// </summary>
        internal static string CliBadProperty {
            get {
                return ResourceManager.GetString("CliBadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: нужно on или off (включить или выключить)..
        /// </summary>
        internal static string CliBadSwitch {
            get {
                return ResourceManager.GetString("CliBadSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: таймеръ — минуты отъ 1 до 65535, часы:минуты (1:30) или off (выключить)..
        /// </summary>
        internal static string CliBadTimer {
            get {
                return ResourceManager.GetString("CliBadTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на яркость {0}.
        /// </summary>
        internal static string CliBrightness {
            get {
                return ResourceManager.GetString("CliBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просушка послѣ выключенія:.
        /// </summary>
        internal static string CliDryAfterOff {
            get {
                return ResourceManager.GetString("CliDryAfterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: {0}.
        /// </summary>
        internal static string CliError {
            get {
                return ResourceManager.GetString("CliError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка въ «{0}»: {1}.
        /// </summary>
        internal static string CliErrorIn {
            get {
                return ResourceManager.GetString("CliErrorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодъ выхода:.
        /// </summary>
        internal static string CliExitCodePrefix {
            get {
                return ResourceManager.GetString("CliExitCodePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неисправность:.
        /// </summary>
        internal static string CliFault {
            get {
                return ResourceManager.GetString("CliFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счётчикъ фильтра сброшенъ..
        /// </summary>
        internal static string CliFilterReset {
            get {
                return ResourceManager.GetString("CliFilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Влажность:.
        /// </summary>
        internal static string CliHumidity {
            get {
                return ResourceManager.GetString("CliHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсвѣтка:.
        /// </summary>
        internal static string CliLight {
            get {
                return ResourceManager.GetString("CliLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсвѣтка: {0}..
        /// </summary>
        internal static string CliLightSet {
            get {
                return ResourceManager.GetString("CliLightSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключена.
        /// </summary>
        internal static string CliLightSwitchOff {
            get {
                return ResourceManager.GetString("CliLightSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на включена.
        /// </summary>
        internal static string CliLightSwitchOn {
            get {
                return ResourceManager.GetString("CliLightSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: у light выключатель (on|off) и яркость (dim|bright) — не больше одного раза каждый (включить|выключить, тусклая|яркая)..
        /// </summary>
        internal static string CliLightTwice {
            get {
                return ResourceManager.GetString("CliLightTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блокировка кнопокъ:.
        /// </summary>
        internal static string CliLock {
            get {
                return ResourceManager.GetString("CliLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режимъ:.
        /// </summary>
        internal static string CliMode {
            get {
                return ResourceManager.GetString("CliMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режимъ: {0}..
        /// </summary>
        internal static string CliModeSet {
            get {
                return ResourceManager.GetString("CliModeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режимъ переключёнъ на слѣдующій..
        /// </summary>
        internal static string CliNextMode {
            get {
                return ResourceManager.GetString("CliNextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невѣрный адресъ «{0}»: нужны четыре числа черезъ точку, напримѣръ 192.168.0.10..
        /// </summary>
        internal static string CliBadAddress {
            get {
                return ResourceManager.GetString("CliBadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвѣстно, къ какому осушителю обращаться: открой программу безъ параметровъ и подключись (адресъ и токенъ запомнятся) или укажи ихъ передъ командами..
        /// </summary>
        internal static string CliNoDevice {
            get {
                return ResourceManager.GetString("CliNoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: нѣтъ значенія — цѣлое число отъ {1} до {2}..
        /// </summary>
        internal static string CliNoHumidity {
            get {
                return ResourceManager.GetString("CliNoHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}»: нѣтъ значенія — режимъ smart, sleep или dry (умный, ночной, сушка)..
        /// </summary>
        internal static string CliNoMode {
            get {
                return ResourceManager.GetString("CliNoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Послѣ адреса {0} нуженъ токенъ — 32 шестнадцатеричныя цифры, затѣмъ команды..
        /// </summary>
        internal static string CliNoToken {
            get {
                return ResourceManager.GetString("CliNoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питаніе:.
        /// </summary>
        internal static string CliPower {
            get {
                return ResourceManager.GetString("CliPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записано: {0} = {1}..
        /// </summary>
        internal static string CliPropertySet {
            get {
                return ResourceManager.GetString("CliPropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}, осталось {1}.
        /// </summary>
        internal static string CliRemaining {
            get {
                return ResourceManager.GetString("CliRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звукъ кнопокъ:.
        /// </summary>
        internal static string CliSound {
            get {
                return ResourceManager.GetString("CliSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключено.
        /// </summary>
        internal static string CliStateOff {
            get {
                return ResourceManager.GetString("CliStateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на включено.
        /// </summary>
        internal static string CliStateOn {
            get {
                return ResourceManager.GetString("CliStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключено..
        /// </summary>
        internal static string CliSwitchedOff {
            get {
                return ResourceManager.GetString("CliSwitchedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включено..
        /// </summary>
        internal static string CliSwitchedOn {
            get {
                return ResourceManager.GetString("CliSwitchedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цѣль:.
        /// </summary>
        internal static string CliTarget {
            get {
                return ResourceManager.GetString("CliTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цѣлевая влажность: {0} %..
        /// </summary>
        internal static string CliTargetSet {
            get {
                return ResourceManager.GetString("CliTargetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура:.
        /// </summary>
        internal static string CliTemperature {
            get {
                return ResourceManager.GetString("CliTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймеръ:.
        /// </summary>
        internal static string CliTimer {
            get {
                return ResourceManager.GetString("CliTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питаніе переключено..
        /// </summary>
        internal static string CliToggled {
            get {
                return ResourceManager.GetString("CliToggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвѣстная команда «{0}»..
        /// </summary>
        internal static string CliUnknownCommand {
            get {
                return ResourceManager.GetString("CliUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управленіе осушителемъ Xiaomi Smart Dehumidifier Lite.
        ///Адресъ и токенъ берутся изъ настроекъ программы (тѣ же, что въ окнѣ).
        ///
        ///  Dehumidifier.exe status                    состояніе
        ///  Dehumidifier.exe on                        включить
        ///  Dehumidifier.exe off                       выключить
        ///  Dehumidifier.exe humidity 40…70            цѣлевая влажность, %
        ///  Dehumidifier.exe mode smart|sleep|dry      режимъ: умный, ночной, сушка бѣлья
        ///  Dehumidifier.exe light on|off dim|bright   подсвѣтка: выключатель  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CliUsage {
            get {
                return ResourceManager.GetString("CliUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогрѣвъ:.
        /// </summary>
        internal static string CliWarming {
            get {
                return ResourceManager.GetString("CliWarming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на суховато (30…39 %).
        /// </summary>
        internal static string ComfortDry {
            get {
                return ResourceManager.GetString("ComfortDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на влажновато (60…69 %).
        /// </summary>
        internal static string ComfortHumid {
            get {
                return ResourceManager.GetString("ComfortHumid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на лучше всего (40…50 %).
        /// </summary>
        internal static string ComfortIdeal {
            get {
                return ResourceManager.GetString("ComfortIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на норма (51…59 %).
        /// </summary>
        internal static string ComfortNormal {
            get {
                return ResourceManager.GetString("ComfortNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на слишкомъ сухо (ниже 30 %).
        /// </summary>
        internal static string ComfortTooDry {
            get {
                return ResourceManager.GetString("ComfortTooDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на слишкомъ влажно (отъ 70 %).
        /// </summary>
        internal static string ComfortTooHumid {
            get {
                return ResourceManager.GetString("ComfortTooHumid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Подключиться.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключено.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключаюсь….
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство {0} не отвѣчаетъ — провѣрь адресъ и сѣть..
        /// </summary>
        internal static string DeviceSilent {
            get {
                return ResourceManager.GetString("DeviceSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Отключиться.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключено.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введи токенъ (32 шестнадцатеричныя цифры) и нажми «Подключиться».
        /// </summary>
        internal static string EnterToken {
            get {
                return ResourceManager.GetString("EnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на свойство нельзя прочесть (-4001).
        /// </summary>
        internal static string Error4001 {
            get {
                return ResourceManager.GetString("Error4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /.
        /// </summary>
        internal static string Error4002 {
            get {
                return ResourceManager.GetString("Error4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нѣтъ такого свойства, дѣйствія или событія (-4003).
        /// </summary>
        internal static string Error4003 {
            get {
                return ResourceManager.GetString("Error4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на внутренняя ошибка устройства (-4004).
        /// </summary>
        internal static string Error4004 {
            get {
                return ResourceManager.GetString("Error4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на недопустимое значеніе (-4005).
        /// </summary>
        internal static string Error4005 {
            get {
                return ResourceManager.GetString("Error4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на недопустимые параметры дѣйствія (-4006).
        /// </summary>
        internal static string Error4006 {
            get {
                return ResourceManager.GetString("Error4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на невѣрный did (-4007).
        /// </summary>
        internal static string Error4007 {
            get {
                return ResourceManager.GetString("Error4007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кодъ {0}.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отсутствуетъ.
        /// </summary>
        internal static string Fault0 {
            get {
                return ResourceManager.GetString("Fault0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бакъ полонъ.
        /// </summary>
        internal static string Fault1 {
            get {
                return ResourceManager.GetString("Fault1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка датчика температуры и влажности.
        /// </summary>
        internal static string Fault2 {
            get {
                return ResourceManager.GetString("Fault2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка датчика медной трубки.
        /// </summary>
        internal static string Fault3 {
            get {
                return ResourceManager.GetString("Fault3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сбой связи.
        /// </summary>
        internal static string Fault4 {
            get {
                return ResourceManager.GetString("Fault4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пора почистить фильтръ.
        /// </summary>
        internal static string Fault5 {
            get {
                return ResourceManager.GetString("Fault5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на размораживаніе.
        /// </summary>
        internal static string Fault6 {
            get {
                return ResourceManager.GetString("Fault6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на заклинило двигатель.
        /// </summary>
        internal static string Fault7 {
            get {
                return ResourceManager.GetString("Fault7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на защита отъ перегрузки.
        /// </summary>
        internal static string Fault8 {
            get {
                return ResourceManager.GetString("Fault8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мало хладагента.
        /// </summary>
        internal static string Fault9 {
            get {
                return ResourceManager.GetString("Fault9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на неизвѣстная ({0}).
        /// </summary>
        internal static string FaultUnknown {
            get {
                return ResourceManager.GetString("FaultUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на яркая.
        /// </summary>
        internal static string LightBright {
            get {
                return ResourceManager.GetString("LightBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тусклая.
        /// </summary>
        internal static string LightDim {
            get {
                return ResourceManager.GetString("LightDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключена.
        /// </summary>
        internal static string LightOff {
            get {
                return ResourceManager.GetString("LightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь возстановлена.
        /// </summary>
        internal static string LinkRestored {
            get {
                return ResourceManager.GetString("LinkRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сушка бѣлья.
        /// </summary>
        internal static string ModeDry {
            get {
                return ResourceManager.GetString("ModeDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ночной.
        /// </summary>
        internal static string ModeSleep {
            get {
                return ResourceManager.GetString("ModeSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на умный.
        /// </summary>
        internal static string ModeSmart {
            get {
                return ResourceManager.GetString("ModeSmart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нѣтъ отвѣта на команду — скорѣе всего, токенъ невѣренъ..
        /// </summary>
        internal static string NoReply {
            get {
                return ResourceManager.GetString("NoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключенъ.
        /// </summary>
        internal static string PowerOff {
            get {
                return ResourceManager.GetString("PowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включенъ.
        /// </summary>
        internal static string PowerOn {
            get {
                return ResourceManager.GetString("PowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство не отдало свойство {0}: {1}.
        /// </summary>
        internal static string ReadRejected {
            get {
                return ResourceManager.GetString("ReadRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить счётчикъ фильтра? Дѣлай это послѣ чистки или замѣны фильтра..
        /// </summary>
        internal static string ResetFilterQuestion {
            get {
                return ResourceManager.GetString("ResetFilterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:0.#} °Ц.
        /// </summary>
        internal static string TemperatureFormat {
            get {
                return ResourceManager.GetString("TemperatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токенъ долженъ состоять изъ 32 шестнадцатеричныхъ цифръ..
        /// </summary>
        internal static string TokenFormat {
            get {
                return ResourceManager.GetString("TokenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тѵпъ {0} не поддерживается..
        /// </summary>
        internal static string TypeNotSupported {
            get {
                return ResourceManager.GetString("TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нѣтъ.
        /// </summary>
        internal static string WarmingNo {
            get {
                return ResourceManager.GetString("WarmingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на идётъ.
        /// </summary>
        internal static string WarmingYes {
            get {
                return ResourceManager.GetString("WarmingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство отклонило запись: {0}.
        /// </summary>
        internal static string WriteRejected {
            get {
                return ResourceManager.GetString("WriteRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚫ &amp;Вести запись.
        /// </summary>
        internal static string RecordStart {
            get {
                return ResourceManager.GetString("RecordStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ■ &amp;Остановить запись.
        /// </summary>
        internal static string RecordStop {
            get {
                return ResourceManager.GetString("RecordStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись идётъ: {0}.
        /// </summary>
        internal static string RecordStarted {
            get {
                return ResourceManager.GetString("RecordStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись остановлена..
        /// </summary>
        internal static string RecordStopped {
            get {
                return ResourceManager.GetString("RecordStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:0.0} г/м³, роса {1:0.0} °Ц.
        /// </summary>
        internal static string WaterFormat {
            get {
                return ResourceManager.GetString("WaterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ≈ {0:t} (черезъ {1}), {2}.
        /// </summary>
        internal static string EtaFormat {
            get {
                return ResourceManager.GetString("EtaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не дойдётъ: предѣлъ ≈ {0:0} %, {1}.
        /// </summary>
        internal static string EtaNever {
            get {
                return ResourceManager.GetString("EtaNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по модели.
        /// </summary>
        internal static string EtaByModel {
            get {
                return ResourceManager.GetString("EtaByModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по наблюденію.
        /// </summary>
        internal static string EtaByObservation {
            get {
                return ResourceManager.GetString("EtaByObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на цѣль достигнута.
        /// </summary>
        internal static string EtaReached {
            get {
                return ResourceManager.GetString("EtaReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выключенъ.
        /// </summary>
        internal static string EtaOff {
            get {
                return ResourceManager.GetString("EtaOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сушка бѣлья — безъ цѣли.
        /// </summary>
        internal static string EtaDry {
            get {
                return ResourceManager.GetString("EtaDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ждётъ конца прогрѣва.
        /// </summary>
        internal static string EtaWarming {
            get {
                return ResourceManager.GetString("EtaWarming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стоитъ — неисправность.
        /// </summary>
        internal static string EtaFault {
            get {
                return ResourceManager.GetString("EtaFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} мин.
        /// </summary>
        internal static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ч {1:00} мин.
        /// </summary>
        internal static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} сут {1} ч.
        /// </summary>
        internal static string DurationDays {
            get {
                return ResourceManager.GetString("DurationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на прогрѣвъ.
        /// </summary>
        internal static string ChartWarming {
            get {
                return ResourceManager.GetString("ChartWarming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:0.0} °Ц.
        /// </summary>
        internal static string CalcDegrees {
            get {
                return ResourceManager.GetString("CalcDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:0.0} г/кг.
        /// </summary>
        internal static string CalcGramsPerKilogram {
            get {
                return ResourceManager.GetString("CalcGramsPerKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на → {0:0.#} %.
        /// </summary>
        internal static string CalcOther {
            get {
                return ResourceManager.GetString("CalcOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:0} г изъ воздуха, {1:0} г съ буферомъ.
        /// </summary>
        internal static string CalcRemove {
            get {
                return ResourceManager.GetString("CalcRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ничего — влажность не выше цѣли.
        /// </summary>
        internal static string CalcNothingToRemove {
            get {
                return ResourceManager.GetString("CalcNothingToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Притокъ влаги сейчасъ: {0:0} г/ч ({1:0.0} л/сутки).
        /// </summary>
        internal static string CalcInflow {
            get {
                return ResourceManager.GetString("CalcInflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осушитель снимаетъ сейчасъ: {0:0} г/ч ({1:0.0} л/сутки).
        /// </summary>
        internal static string CalcRemoval {
            get {
                return ResourceManager.GetString("CalcRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безъ осушителя влажность пойдётъ къ {0:0} % (τ = {1:0.0} ч).
        /// </summary>
        internal static string CalcWithout {
            get {
                return ResourceManager.GetString("CalcWithout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безъ осушителя: воздухообмѣна нѣтъ — источники поднимаютъ влажность безъ предѣла.
        /// </summary>
        internal static string CalcWithoutLimit {
            get {
                return ResourceManager.GetString("CalcWithoutLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Съ осушителемъ безъ остановокъ — къ {0:0} % (τ = {1:0.0} ч).
        /// </summary>
        internal static string CalcWith {
            get {
                return ResourceManager.GetString("CalcWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До цѣли {0:0} %: {1}.
        /// </summary>
        internal static string CalcEta {
            get {
                return ResourceManager.GetString("CalcEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До цѣли {0:0} % не дойдётъ: предѣлъ {1:0} %.
        /// </summary>
        internal static string CalcNever {
            get {
                return ResourceManager.GetString("CalcNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цѣль {0:0} % уже достигнута.
        /// </summary>
        internal static string CalcReached {
            get {
                return ResourceManager.GetString("CalcReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы держать {0:0} %, нужна паспортная производительность не меньше {1:0.0} л/сутки.
        /// </summary>
        internal static string CalcNeeded {
            get {
                return ResourceManager.GetString("CalcNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ниже ≈ {0:0} % компрессорный осушитель почти не сушитъ.
        /// </summary>
        internal static string CalcTooLow {
            get {
                return ResourceManager.GetString("CalcTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Въ записяхъ нѣтъ ровныхъ отрѣзковъ (не короче 10 минутъ) — уточнить нечѣмъ..
        /// </summary>
        internal static string CalcFromRecordsNone {
            get {
                return ResourceManager.GetString("CalcFromRecordsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По записямъ: отрѣзковъ «выключенъ» — {0}, «осушаетъ» — {1}..
        /// </summary>
        internal static string CalcFromRecordsDone {
            get {
                return ResourceManager.GetString("CalcFromRecordsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключенъ къ {0}.
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
    }
}
